// <auto-generated />
using System;
using GameShelf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameShelf.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameShelf.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An epic open-world RPG adventure in a dark fantasy universe",
                            Developer = "CD Projekt Red",
                            GenreId = 2,
                            IsCompleted = true,
                            PlatformId = 1,
                            Price = 39.99m,
                            Publisher = "CD Projekt",
                            PurchaseDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 10,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Follow Kratos and Atreus in Norse mythology",
                            Developer = "Santa Monica Studio",
                            GenreId = 1,
                            IsCompleted = false,
                            PlatformId = 2,
                            Price = 49.99m,
                            Publisher = "Sony Interactive Entertainment",
                            PurchaseDate = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 9,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Master Chief returns in this epic sci-fi shooter",
                            Developer = "343 Industries",
                            GenreId = 1,
                            IsCompleted = false,
                            PlatformId = 3,
                            Price = 59.99m,
                            Publisher = "Xbox Game Studios",
                            Rating = 8,
                            ReleaseDate = new DateTime(2021, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Halo Infinite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Explore the vast kingdom of Hyrule in this open-world adventure",
                            Developer = "Nintendo EPD",
                            GenreId = 5,
                            IsCompleted = true,
                            PlatformId = 4,
                            Price = 59.99m,
                            Publisher = "Nintendo",
                            PurchaseDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 10,
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda: Breath of the Wild"
                        });
                });

            modelBuilder.Entity("GameShelf.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fast-paced games focusing on physical challenges",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Role-playing games with character development",
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Games requiring tactical thinking and planning",
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sports simulation and competition games",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Story-driven exploration games",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Games simulating real-world activities",
                            Name = "Simulation"
                        });
                });

            modelBuilder.Entity("GameShelf.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Personal Computer gaming platform",
                            Manufacturer = "Various",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sony's next-generation gaming console",
                            Manufacturer = "Sony",
                            Name = "PlayStation 5"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Microsoft's powerful gaming console",
                            Manufacturer = "Microsoft",
                            Name = "Xbox Series X"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hybrid home and portable console",
                            Manufacturer = "Nintendo",
                            Name = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("GameShelf.Models.Game", b =>
                {
                    b.HasOne("GameShelf.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameShelf.Models.Platform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameShelf.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameShelf.Models.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
